.TH FLOBOPUYO 6 "August 23, 2004"
.SH NAME
flobopuyo \- A clone of the Japanese PuyoPuyo game
.SH SYNOPSIS
.B flobopuyo
.SH DESCRIPTION
The goal of
.B flobopuyo
is to make groups of four or more Puyos (coloured
bubbles) to make them explode and send bad ghost Puyos to your oponent.
You win the game if your oponent reaches the top of the board. You can
play against computer or another human.
.br
The game has nice graphics and animations as well as music and sound effects.
.SH OPTIONS
None.
.SH BUGS
Please report any bugs you find to <iosteam@ios-software.com>.
.SH LICENSE
.B flobopuyo
is covered by the GNU General Public License (GPL).
.SH SEE ALSO
.BR xpuyopuyo (6),
.BR kfouleggs (6).
.SH AUTHOR
Florent Boudet <flobo@ios-software.com>
.br
Guillaume Borios <gyom@ios-software.com>
.br
Jean-Christophe Hoelt <jeko@ios-software.com>
.PP
This manual page was written by Uwe Hermann <uwe@debian.org>,
for the Debian project (but may be used by others).
