name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Ubuntu, os: ubuntu-latest, shell: sh }
        - { name: macOS,  os: macos-latest,  shell: sh }

    steps:
    - uses: actions/checkout@v3

    - name: Setup GNU/Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install \
            libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl1.2-dev ninja-build

    - name: Setup macOS dependencies
      if: runner.os == 'macOS'
      run: |
        brew install \
            sdl_image sdl_mixer sdl12-compat ninja

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug --verbose --parallel
